# Generated by Django 6.0.5 on 2026-05-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Operacion",
            fields=[
                ("id_operacion", models.AutoField(primary_key=True, serialize=False)),
                ("numero1", models.FloatField()),
                ("numero2", models.FloatField()),
                ("operacion", models.CharField(max_length=20)),
                ("resultado", models.FloatField()),
            ],
            options={
                "verbose_name": "Operacion",
                "verbose_name_plural": "Operaciones",
                "db_table": "operacion",
            },
        ),
    ]
